# Setup container
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:ubuntu
RUN apt-get update 

# Add steam user
# RUN useradd -ms /bin/bash steam
# USER steam

# Install SteamCMD

# RUN apt update && apt install -y software-properties-common
# RUN add-apt-repository -y multiverse
# RUN dpkg --add-architecture i386
# RUn apt update
# RUN apt install -y steamcmd